和文に対応
ibuki2003/discord_cw_bot pull request #12
Opened 2024-01-05 14:16 UTC by Graphium314

和文モールスを追加

2024-01-05 15:34 UTC, taka231 requested changes

2024-01-05 15:34 UTC, taka231 commented on src/morse.rs
> +        'ヰ' => (4, 0b0100),
ヰは.-..-っぽい?

2024-01-05 15:34 UTC, taka231 commented on src/morse.rs
> +        'ユ' => (4, 0b1001),
ユは-..--っぽい

2024-01-05 15:34 UTC, taka231 commented on src/morse.rs
> +        'ヱ' => (4, 0b0110),
ヱは.--..っぽい

2024-01-05 15:34 UTC, taka231 commented on src/morse.rs
> +        'メ' => (4, 0b1000),
メは-...-っぽい

2024-01-05 15:34 UTC, taka231 commented on src/morse.rs
> +        'ミ' => (4, 0b0010),
ミは..-.-っぽい

2024-01-05 15:34 UTC, taka231 commented on src/morse.rs
> +        'ヒ' => (4, 0b1100),
ヒは--..-っぽい

2024-01-05 15:34 UTC, taka231 commented on src/morse.rs
> +        'モ' => (4, 0b1001),
モは-..-.っぽい

2024-01-06 18:55 UTC, ibuki2003 commented on src/morse.rs
> +        'ヰ' => (4, 0b0100),
`ゐ` `ゑ`はワ行です…

2024-01-07 01:34 UTC, Graphium314 commented
指摘の修正をしました

2024-01-24 13:44 UTC, taka231 approved these changes

2024-01-24 13:45 UTC, ibuki2003 approved these changes
LGTM

2024-01-24 13:45 UTC, merged